2021/01/23 07:22:55 [error] 21#21: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1"
2021/01/23 07:22:58 [error] 21#21: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2021/01/23 08:45:02 [error] 21#21: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1"
2021/01/23 08:45:04 [error] 21#21: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2021/01/23 10:10:27 [error] 21#21: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /post/2019/09/gpg-keyserver-receive-failed-server-indicated-a-failure.html HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "einverne.github.io", referrer: "https://www.baidu.com/link?url=XJiyn1Ylj7J5IcnSWvTCmFlxa5RI6WFqRgHwCkdy6LYm-QKz5LuRVgTndyN80rBuJHu3MLIyg4V76mzJ8bZe5p_HExXy2qg64YRg8ZWBiVR9r6a-CFAKf-P-NKinyrmVdoCr28cl2LxoR57THrLwLa&wd=&eqid=ce046b45000270ee00000006600bf5e1"
2021/01/23 10:10:29 [error] 21#21: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "einverne.github.io", referrer: "http://einverne.github.io/post/2019/09/gpg-keyserver-receive-failed-server-indicated-a-failure.html"
2021/01/23 11:08:35 [error] 20#20: *1 upstream prematurely closed connection while reading response header from upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1"
2021/01/23 11:08:36 [error] 20#20: *1 upstream prematurely closed connection while reading response header from upstream, client: 172.21.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2021/01/25 12:03:25 [error] 20#20: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1"
2021/01/25 12:03:26 [error] 20#20: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2021/01/25 12:04:42 [error] 20#20: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /admin HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1"
2021/01/25 12:04:43 [error] 20#20: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1", referrer: "http://127.0.0.1/admin"
2021/01/25 12:04:45 [error] 20#20: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2021/01/25 12:04:54 [error] 20#20: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /admin HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1"
2021/01/25 12:04:54 [error] 20#20: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1", referrer: "http://127.0.0.1/admin"
2021/01/25 12:06:42 [error] 20#20: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1", referrer: "http://127.0.0.1/static/img/find_icon-shopping.27495d60.png"
2021/01/25 12:20:40 [emerg] 32#32: bind() to 0.0.0.0:80 failed (98: Address already in use)
2021/01/25 12:20:40 [emerg] 32#32: bind() to 0.0.0.0:80 failed (98: Address already in use)
2021/01/25 12:20:40 [emerg] 32#32: bind() to 0.0.0.0:80 failed (98: Address already in use)
2021/01/25 12:20:40 [emerg] 32#32: bind() to 0.0.0.0:80 failed (98: Address already in use)
2021/01/25 12:20:40 [emerg] 32#32: bind() to 0.0.0.0:80 failed (98: Address already in use)
2021/01/25 12:20:40 [emerg] 32#32: still could not bind()
2021/01/25 12:21:42 [notice] 37#37: signal process started
2021/01/25 12:21:56 [error] 38#38: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1", referrer: "http://127.0.0.1/admin"
2021/01/25 12:22:01 [error] 38#38: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1"
2021/01/25 12:22:01 [error] 38#38: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2021/01/25 12:22:03 [error] 38#38: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1"
2021/01/25 12:22:04 [error] 38#38: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2021/01/25 12:43:46 [error] 38#38: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1"
2021/01/25 12:43:47 [error] 38#38: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2021/01/25 12:51:17 [error] 38#38: *27 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1"
2021/01/25 12:51:18 [error] 38#38: *27 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2021/01/26 07:08:01 [error] 20#20: *1 upstream prematurely closed connection while reading response header from upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1"
2021/01/26 07:17:22 [error] 20#20: *4 upstream prematurely closed connection while reading response header from upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1"
2021/01/26 07:25:41 [error] 20#20: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1"
2021/01/26 09:45:03 [error] 20#20: *27 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1"
2021/01/26 09:48:45 [error] 20#20: *30 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://172.21.0.4:8000", host: "127.0.0.1"
